name: '🔎 Gemini Review'

on:
  workflow_call:
    inputs:
      additional_context:
        type: 'string'
        description: 'Any additional context from the request'
        required: false

concurrency:
  group: '${{ github.workflow }}-review-${{ github.event_name }}-${{ github.event.pull_request.number || github.event.issue.number }}'
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  review:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5

      - name: 'Run Gemini pull request review'
        uses: 'google-github-actions/run-gemini-cli@v0' # ratchet:exclude
        id: 'gemini_pr_review'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN || github.token }}'
          ISSUE_TITLE: '${{ github.event.pull_request.title || github.event.issue.title }}'
          ISSUE_BODY: '${{ github.event.pull_request.body || github.event.issue.body }}'
          PULL_REQUEST_NUMBER: '${{ github.event.pull_request.number || github.event.issue.number }}'
          REPOSITORY: '${{ github.repository }}'
          ADDITIONAL_CONTEXT: '${{ inputs.additional_context }}'
        with:
          gemini_api_key: '${{ secrets.GEMINI_API_KEY }}'
          settings: |-
            {
              "model": {
                "maxSessionTurns": 25
              },
              "mcpServers": {
                "github": {
                  "command": "docker",
                  "args": [
                    "run",
                    "-i",
                    "--rm",
                    "-e",
                    "GITHUB_PERSONAL_ACCESS_TOKEN",
                    "ghcr.io/github/github-mcp-server"
                  ],
                  "includeTools": [
                    "add_comment_to_pending_review",
                    "create_pending_pull_request_review",
                    "get_pull_request_diff",
                    "get_pull_request_files",
                    "get_pull_request",
                    "submit_pending_pull_request_review"
                  ],
                  "env": {
                    "GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_TOKEN}"
                  }
                }
              },
              "tools": {
                "core": [
                "run_shell_command(cat)",
                "run_shell_command(echo)",
                "run_shell_command(grep)",
                "run_shell_command(head)",
                "run_shell_command(tail)"
                ]
              }
            }
          prompt: |-
            ## Simplified Role

            You are a tool for debugging GitHub workflows. Your only task is to summarize the changes in a pull request without performing a detailed code review.

            ## Input Data

            - Retrieve the GitHub repository name from the environment variable "${REPOSITORY}".
            - Retrieve the GitHub pull request number from the environment variable "${PULL_REQUEST_NUMBER}".
            - Use `mcp__github__get_pull_request` to get basic information about the pull request.
            - Use `mcp__github__get_pull_request_files` to get the list of files changed.
            - Use `mcp__github__get_pull_request_diff` to get the diff.

            ## Simple Execution Workflow

            1. **Get Data:** Collect basic information about the PR using the tools above.

            2. **Create Summary:** Create a brief summary of changes (files changed, lines added/removed).

            3. **Submit Summary:** 
               - Call `mcp__github__create_pending_pull_request_review`
               - Call `mcp__github__submit_pending_pull_request_review` with a simple summary:

                <SUMMARY>
                ## Changes Summary

                [List of files changed and basic statistics]

                ## Files Modified
                - [List files with brief description of changes]
                </SUMMARY>
